import lvlUpCharacter,classDefine,os,createSaveCharacter,fightGenerator

v = classDefine.tank("george",10)
# v.pseudo
# ,v.lvl,v.hpbase,v.dmgBase,v.armor
w = classDefine.cac("Roberto",1)
x = classDefine.tank("Emile",1)
y = classDefine.dist("Alfred",1)
u = classDefine.cac("cac2",1)
v = classDefine.tank("tank2",1)
t = classDefine.dist("dist2",1)
# w.pseudo,w.lvl,w.hpbase,w.dmgBase,w.armor
# print (v)
print (w)
print (repr(w))
print (repr(y))
print (repr(x))
# createSaveCharacter.save(v,w)
fightGenerator.encounter("A",w,x,y)
fightGenerator.encounter("A",t)
fightGenerator.encounter("A",u)
fightGenerator.encounter("A",v)
print (repr(t))
print (repr(u))
print (repr(v))
print (repr(w))
print (repr(y))
print (repr(x))
# lvlUpCharacter.lvlUp(v)
fightGenerator.encounter("B",w,x,y)
fightGenerator.encounter("B",t)
fightGenerator.encounter("B",u)
fightGenerator.encounter("B",v)
print (repr(t))
print (repr(u))
print (repr(v))
print (repr(w))
print (repr(y))
print (repr(x))


